/**
 * @deprecated Phase B (plan v3 U9b 范围)：flow 流量导出在 P0 暂下线，boss P1 重建。
 * Phase B-α 仅打标；完整删除是 Phase B 后续 PR。
 */
import type { CanonicalTsnProjectV0, TsnFlow, TsnNode } from "../domain/canonical";

interface SourceApp {
  flow: TsnFlow;
  sourceNode: TsnNode;
  destinationNode: TsnNode;
}

interface SinkApp {
  node: TsnNode;
  localPort: number;
}

interface NodeApps {
  node: TsnNode;
  sources: SourceApp[];
  sinks: SinkApp[];
}

export function exportInetTrafficIni(project: CanonicalTsnProjectV0): string {
  const sourceApps = buildSourceApps(project);
  const sinkApps = buildSinkApps(project, sourceApps);

  return [
    "# Generated by TSN Agent.",
    "# First UDP traffic layer only: no gPTP, TAS/GCL, CBS, PSFP, FRER, or planner result replay.",
    "",
    "# UDP applications",
    ...renderNodeApps(project, sourceApps, sinkApps),
    "",
  ].join("\n");
}

function buildSourceApps(project: CanonicalTsnProjectV0): SourceApp[] {
  return [...project.flows]
    .sort((left, right) => left.numericId - right.numericId)
    .map((flow) => {
      const sourceNode = findNode(project, flow.source.nodeId, flow.id, "source");
      const destinationNode = findNode(project, flow.destination.nodeId, flow.id, "destination");

      return {
        flow,
        sourceNode,
        destinationNode,
      };
    })
    .sort((left, right) => compareByTopologyOrder(project, left.sourceNode, right.sourceNode) || left.flow.numericId - right.flow.numericId);
}

function buildSinkApps(project: CanonicalTsnProjectV0, sourceApps: SourceApp[]): SinkApp[] {
  const sinkByKey = new Map<string, SinkApp>();

  for (const sourceApp of sourceApps) {
    const key = `${sourceApp.destinationNode.id}:${sourceApp.flow.destination.udpPort}`;

    if (!sinkByKey.has(key)) {
      sinkByKey.set(key, {
        node: sourceApp.destinationNode,
        localPort: sourceApp.flow.destination.udpPort,
      });
    }
  }

  return [...sinkByKey.values()].sort((left, right) => compareByTopologyOrder(project, left.node, right.node) || left.localPort - right.localPort);
}

function renderNodeApps(project: CanonicalTsnProjectV0, sourceApps: SourceApp[], sinkApps: SinkApp[]): string[] {
  const nodeApps = mergeNodeApps(project, sourceApps, sinkApps);
  const lines: string[] = [];

  for (const nodeApp of nodeApps) {
    const nedNodeId = safeNedId(nodeApp.node.id);
    const totalApps = nodeApp.sources.length + nodeApp.sinks.length;
    lines.push(`*.${nedNodeId}.numApps = ${totalApps}`);

    nodeApp.sources.forEach((app, index) => {
      lines.push(`# ${app.flow.name}`);
      lines.push(`*.${nedNodeId}.app[${index}].typename = "UdpSourceApp"`);
      lines.push(`*.${nedNodeId}.app[${index}].io.destAddress = "${safeNedId(app.destinationNode.id)}"`);
      lines.push(`*.${nedNodeId}.app[${index}].io.destPort = ${app.flow.destination.udpPort}`);
      lines.push(`*.${nedNodeId}.app[${index}].source.packetLength = ${app.flow.frameSizeBytes}B`);
      lines.push(`*.${nedNodeId}.app[${index}].source.productionInterval = ${app.flow.periodUs}us`);
    });

    nodeApp.sinks.forEach((app, sinkIndex) => {
      const index = nodeApp.sources.length + sinkIndex;
      lines.push(`*.${nedNodeId}.app[${index}].typename = "UdpSinkApp"`);
      lines.push(`*.${nedNodeId}.app[${index}].io.localPort = ${app.localPort}`);
    });
  }

  return lines;
}

function mergeNodeApps(project: CanonicalTsnProjectV0, sourceApps: SourceApp[], sinkApps: SinkApp[]): NodeApps[] {
  const nodeAppsById = new Map<string, NodeApps>();

  for (const source of sourceApps) {
    getOrCreateNodeApps(nodeAppsById, source.sourceNode).sources.push(source);
  }

  for (const sink of sinkApps) {
    getOrCreateNodeApps(nodeAppsById, sink.node).sinks.push(sink);
  }

  return [...nodeAppsById.values()].sort((left, right) => compareByTopologyOrder(project, left.node, right.node));
}

function getOrCreateNodeApps(nodeAppsById: Map<string, NodeApps>, node: TsnNode): NodeApps {
  const existing = nodeAppsById.get(node.id);

  if (existing) {
    return existing;
  }

  const next = {
    node,
    sources: [],
    sinks: [],
  };
  nodeAppsById.set(node.id, next);
  return next;
}

function findNode(project: CanonicalTsnProjectV0, nodeId: string, flowId: string, endpointRole: string): TsnNode {
  const node = project.topology.nodes.find((candidate) => candidate.id === nodeId);

  if (!node) {
    throw new Error(`Cannot export INET traffic: flow ${flowId} references missing ${endpointRole} node ${nodeId}.`);
  }

  return node;
}

function compareByTopologyOrder(project: CanonicalTsnProjectV0, left: TsnNode, right: TsnNode): number {
  return project.topology.nodes.indexOf(left) - project.topology.nodes.indexOf(right);
}

function safeNedId(value: string): string {
  return value.replaceAll("-", "_");
}
